version: '3'
services:
  python-flask-server:
    build: ./python-flask-server
    volumes:
      - ./python-flask-server:/usr/src/app
    ports:
      - "8080:8080"
    links:
      - redis
    restart: always
  redis:
    image: redis
    restart: always
