version: '3'
services:
  flask:
    build: ./flask
    volumes:
      - ./flask:/usr/src/app
    ports:
      - "8080:8080"
#    links:
#      - redis
    environment:
      FLASK_DEBUG: 1
#    restart: always
#  redis:
#    image: redis
##    restart: always