# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Investor(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, phone: str=None, email: str=None, password: str=None):  # noqa: E501
        """Investor - a model defined in Swagger

        :param id: The id of this Investor.  # noqa: E501
        :type id: int
        :param name: The name of this Investor.  # noqa: E501
        :type name: str
        :param phone: The phone of this Investor.  # noqa: E501
        :type phone: str
        :param email: The email of this Investor.  # noqa: E501
        :type email: str
        :param password: The password of this Investor.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'phone': str,
            'email': str,
            'password': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'phone': 'phone',
            'email': 'email',
            'password': 'password'
        }

        self._id = id
        self._name = name
        self._phone = phone
        self._email = email
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'Investor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Investor of this Investor.  # noqa: E501
        :rtype: Investor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Investor.


        :return: The id of this Investor.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Investor.


        :param id: The id of this Investor.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Investor.


        :return: The name of this Investor.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Investor.


        :param name: The name of this Investor.
        :type name: str
        """

        self._name = name

    @property
    def phone(self) -> str:
        """Gets the phone of this Investor.


        :return: The phone of this Investor.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this Investor.


        :param phone: The phone of this Investor.
        :type phone: str
        """

        self._phone = phone

    @property
    def email(self) -> str:
        """Gets the email of this Investor.


        :return: The email of this Investor.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Investor.


        :param email: The email of this Investor.
        :type email: str
        """

        self._email = email

    @property
    def password(self) -> str:
        """Gets the password of this Investor.


        :return: The password of this Investor.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this Investor.


        :param password: The password of this Investor.
        :type password: str
        """

        self._password = password
