---
swagger: "2.0"
info:
  description: "SunVibe is a Solar Energy Platform where small investors - crowd founders\
    \ - together finance solar panel installation on the roof of other people’s -\
    \ roof lenders - house.\nThe installation is constructing by authorized Installers,\
    \ but the quality assurance and monitoring done by SunVibe.\n"
  version: "0.1.0"
  title: "SunVibe API"
  termsOfService: "http://sunvibe.vn/terms"
  contact:
    email: "apiteam@sunvibe.vn"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "api.sunvibe.vn"
basePath: "/v1"
tags:
- name: "bid"
  description: "Bid operations on SunVibeToken marketplace"
- name: "ask"
  description: "Ask operations on SunVibeToken marketplace"
- name: "user"
  description: "User operations, sign-in, log-in, list etc."
schemes:
- "http"
paths:
  /bids:
    get:
      tags:
      - "bid"
      summary: "List Bids"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "list_bids"
      x-swagger-router-controller: "swagger_server.controllers.bid_controller"
    post:
      tags:
      - "bid"
      summary: "Add a new bid to the market"
      description: "Add token buying offering"
      operationId: "add_bid"
      security:
      - OAuth2:
        - "investor"
      x-swagger-router-controller: "swagger_server.controllers.bid_controller"
  /bids/{id}:
    get:
      tags:
      - "bid"
      summary: "Get bid details by ID"
      description: "Returns a bid based on a single ID"
      operationId: "get_bid"
      x-swagger-router-controller: "swagger_server.controllers.bid_controller"
    put:
      tags:
      - "bid"
      summary: "Update an existing bid"
      description: "Modify bid status only"
      operationId: "update_bid"
      security:
      - OAuth2:
        - "investor"
      x-swagger-router-controller: "swagger_server.controllers.bid_controller"
    delete:
      tags:
      - "bid"
      summary: "Deletes and existing bid"
      description: "Deletes a single bet based on the ID supplied"
      operationId: "del_bid"
      security:
      - OAuth2:
        - "investor"
      x-swagger-router-controller: "swagger_server.controllers.bid_controller"
  /fok-bids:
    post:
      tags:
      - "bid"
      summary: "Fill or kill bids"
      description: "Only accept existing ask - selling request"
      operationId: "fok_bid"
      security:
      - OAuth2:
        - "investor"
      x-swagger-router-controller: "swagger_server.controllers.bid_controller"
  /asks:
    get:
      tags:
      - "ask"
      summary: "List Asks"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "list_asks"
      x-swagger-router-controller: "swagger_server.controllers.ask_controller"
    post:
      tags:
      - "ask"
      summary: "Add a new ask to the market"
      description: "Add token buying offering"
      operationId: "add_ask"
      security:
      - OAuth2:
        - "investor"
      x-swagger-router-controller: "swagger_server.controllers.ask_controller"
  /asks/{id}:
    get:
      tags:
      - "ask"
      description: "Returns a user based on a single ID, if the user does not have\
        \ access to the pet"
      operationId: "get_ask"
      x-swagger-router-controller: "swagger_server.controllers.ask_controller"
    put:
      tags:
      - "ask"
      summary: "Update an existing ask"
      description: ""
      operationId: "update_ask"
      security:
      - OAuth2:
        - "investor"
      x-swagger-router-controller: "swagger_server.controllers.ask_controller"
    delete:
      tags:
      - "ask"
      description: "deletes a single bet based on the ID supplied"
      operationId: "del_ask"
      security:
      - OAuth2:
        - "investor"
      x-swagger-router-controller: "swagger_server.controllers.ask_controller"
  /fok-asks:
    post:
      tags:
      - "ask"
      summary: "Fill or kill asks"
      description: "Only accept existing ask - selling request"
      operationId: "fok_ask"
      security:
      - OAuth2:
        - "investor"
      x-swagger-router-controller: "swagger_server.controllers.ask_controller"
  /users:
    get:
      tags:
      - "user"
      summary: "Returns all users in the database."
      description: "Only the admin can access this."
      operationId: "list_users"
      security:
      - OAuth2:
        - "admin"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
    post:
      tags:
      - "user"
      summary: "Creates a new user"
      description: "Only the admin user can create users."
      operationId: "add_user"
      security:
      - OAuth2:
        - "admin"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /users/{id}:
    get:
      tags:
      - "user"
      summary: "Retrieves a user"
      description: "Users can only retrieve their own account, except for the admin,\
        \ who can retrieve anyone."
      operationId: "get_user"
      security:
      - OAuth2:
        - "registered"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
    put:
      tags:
      - "user"
      summary: "Update a user"
      description: "Users can only update their own account, except the admin, who\
        \ can edit anyone."
      operationId: "update_user"
      security:
      - OAuth2:
        - "registered"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
    delete:
      tags:
      - "user"
      summary: "Deletes a user"
      description: "Users can only delete their own account, admin can delete everyone\
        \ else."
      operationId: "del_user"
      security:
      - OAuth2:
        - "investor"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /users/login:
    post:
      tags:
      - "user"
      summary: "Logs in already registered users and admin"
      description: ""
      operationId: "user_login"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /users/{id}/logout:
    post:
      tags:
      - "user"
      summary: "Logs out the given user"
      description: "Users can only log themselves out, admin can log-out anyone."
      operationId: "user_logout"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
securityDefinitions:
  BasicAuth:
    type: "basic"
  ApiKeyAuth:
    type: "apiKey"
    name: "X-API-Key"
    in: "header"
  OAuth2:
    type: "oauth2"
    authorizationUrl: "https://sunvibe.vn/oauth/authorize"
    tokenUrl: "https://sunvibe.vn/oauth/token"
    flow: "accessCode"
    scopes:
      investor: "Grants investor access. Users with confirmed registration."
      registered: "Grants registered user access."
      admin: "Grants access to administrative information."